// vue_js_vuex/src/components/Title.vue
<template>
  <div class="title animated fadeInDown">
    <span>TO DO LIST</span>
  </div>
</template>

<script>
export default {};
</script>

<style scoped>
.title {
  width: 100%;
  color: white;
  font-size: 30px;
  font-weight: bold;
  font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
  text-align: center;
  padding: 30px 0;
}
</style>

// react_ts_mobx_eos/src/components/Title.tsx
import * as React from 'react'
import styled from 'styled-components';

const Text = styled.div`
  font-size: 30px;
  text-align: center;
  color: white;
  padding: 50px 0 20px 0;
`;

export default function Title({ text }: { text: string }) {
  return <Text className="animated fadeInDown">{text}</Text>
}
