// vue_js/src/components/List.vue
<template>
  <div class="list animated">
    <div class="tip animated fadeInLeft" v-if="list.length === 0">{{ '暂无待办事项'}}</div>
    <div class="tip animated" v-if="list.length !== 0">{{ '向左滑动可进行操作待办事项，点击可查看详情' }}</div>
    <van-tabs
      v-model="active"
      color="#0f4c81"
      title-active-color="#0f4c81"
      @change="tabChange"
      v-if="list.length !== 0"
    >
      <van-tab v-for="index in tabList" :title="index" :key="index">
        <div class="tip animated fadeInDown" style="color: gray;" v-show="newList.length === 0">{{'暂无事项'}}</div>
        <van-swipe-cell
          class="item animated fadeInDown"
          v-for="(item,i) in newList"
          :key="i"
          :before-close="beforeClose"
          :name="i"
        >
          <div
            class="content"
            @click="details(item.value)"
            :style="{color: item.isDone ? 'gray' : '#0F4c81'}"
          >
            <span style="margin-right: 7px">{{ i+1+'.' }}</span>
            <span class="text">{{ item.value }}</span>
          </div>
          <template slot="right" v-if="!item.isDone">
            <van-button class="btn" square type="primary" text="完成" />
          </template>
          <template slot="right" v-if="item.isDone">
            <van-button class="btn" square type="danger" text="删除" />
          </template>
        </van-swipe-cell>
      </van-tab>
    </van-tabs>
  </div>
</template>

<script>
import { Dialog } from "vant";

export default {
  props: {
    list: {
      type: Array,
      default: () => []
    }
  },
  data() {
    const list = this.list;
    return {
      tabList: ["全部事项", "未完成", "已完成"],
      active: 0,
      newList: list
    };
  },
  methods: {
    details(val) {
      Dialog({
        message: val,
        width: 260,
        closeOnClickOverlay: true,
        showConfirmButton: false
      }).catch(() => {});
    },
    handle(instance, name) {
      Dialog.confirm({
        message: "确定进行此项操作吗？",
        width: 260
      })
        .then(() => {
          this.$emit("handle", this.newList[name].id);
          instance.close();
        })
        .catch(() => {});
    },
    beforeClose({ position, instance, name }) {
      switch (position) {
        case "outside":
          instance.close();
          break;
        case "right":
          instance.close();
          this.handle(instance, name);
          break;
      }
    },
    tabChange(e) {
      let list = localStorage.getItem("list") || [];
      list = JSON.parse(list);
      switch (e) {
        case 0:
          this.newList = list;
          break;
        case 1:
          this.newList = list.filter(item => {
            return !item.isDone;
          });
          break;
        default:
          this.newList = list.filter(item => {
            return item.isDone;
          });
          break;
      }
    },
    updateData() {
      this.tabChange(this.active);
    }
  }
};
</script>
 
<style scoped>
.list {
  width: 100%;
  height: 100%;
  background-color:#0f4c81;
  margin-top: 20px;
  border-radius: 3px;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

.item {
  width: 100%;
  min-height: 50px;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  border-top: 1px solid #f1efe0;
  font-size: 16px;
}

.content {
  width: calc(100vw - 60px);
  padding: 10px 10px;
  min-height: 30px;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  overflow: hidden;
  border-right: 0px solid white;
  background-color: white
}

.btn {
  height: 100%;
  line-height: 100%;
}

.tip {
  color: #0f4c81;
  font-size: 12px;
  padding: 5px;
  width: calc(100vw - 50px);
  background-color: white
}

.text {
  text-align: left;
  width: 100%;
}
</style>

// react_ts_mobx/src/components/List.tsx
import React, { Component } from 'react';
import { themeColor } from '../config/const'
import styled from 'styled-components'
import { Tabs } from 'antd-mobile';
import Item from './Item'
import Store from '../store';
import {  inject, observer } from 'mobx-react';

// props要接受的值
interface IProps {
  store?: Store;
}

export interface listItemProps {
  value: string,
  isDone: boolean,
  key: string
} 

const ListBox = styled.div`
  max-height: '70%';
  margin-top: 20px;
  background-color: ${ themeColor};
`

const TipText = styled.div`
  color: ${ themeColor};
  background-color: white;
  text-align: center;
  padding: 5px;
  font-size: 12px;
`

const TipText2 = styled(TipText)`
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  border-bottom-color: #f1efe0;
  border-bottom-width: 1px;
`

const tabs = [
  { title: '全部事项', sub: '1' },
  { title: '未完成', sub: '2' },
  { title: '已完成', sub: '3' }
];

@inject("store")
@observer
export default class Lists extends Component<IProps> {

  componentDidMount(){
    this.props.store!.readListStore()
  }

  render() {
    const list: listItemProps[] = this.props.store!.list
    const tabList: listItemProps[] = this.props.store!.tabList

    return (<ListBox>
      {/* 提示栏 */}
      {list.length === 0 ? <TipText className="animated fadeInLeft">暂无待办事项</TipText> : <TipText2 className="animated fadeInRight">向左滑动可进行操作待办事项，点击可查看详情</TipText2>}

      {/* 标签栏 */}
      {list.length !== 0 ? <Tabs tabs={tabs}
        initialPage={0}
        swipeable={false}
        tabBarActiveTextColor={themeColor}
        tabBarUnderlineStyle={{ color: themeColor }}
        onTabClick={(_, i) => { this.props.store!.getTabList(i) }}
      >
        <div>{tabList.map((item, index) => <Item item={item} index={index} key={index} handleClick={key=>this.props.store!.handleDone(key)}/>)}</div>
        <div>{tabList.map((item, index) => <Item item={item} index={index} key={index} handleClick={key=>this.props.store!.handleDone(key)}/>)}</div>
        <div>{tabList.map((item, index) => <Item item={item} index={index} key={index} handleClick={key=>this.props.store!.handleDone(key)}/>)}</div>
      </Tabs> : null}

      {tabList.length === 0 && list.length !== 0 && <TipText2 className="animated fadeInDown">{'暂无事项'}</TipText2>}
    </ListBox>
    )
  }
}
